# Generated by Django 5.2.8 on 2026-02-02 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('domain', models.CharField(blank=True, db_index=True, max_length=100)),
                ('company_description', models.TextField(blank=True)),
                ('company_size', models.CharField(blank=True, max_length=50)),
                ('verification', models.BooleanField(db_index=True, default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField()),
                ('skills', models.JSONField(blank=True, default=list)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(db_index=True, max_length=100)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full_time', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], db_index=True, default='published', max_length=20)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.employer')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='employers_j_status_423370_idx'), models.Index(fields=['location', 'status'], name='employers_j_locatio_543494_idx'), models.Index(fields=['title', 'status'], name='employers_j_title_f32a03_idx'), models.Index(fields=['job_type', 'status'], name='employers_j_job_typ_e00fb2_idx'), models.Index(fields=['salary_min', 'salary_max'], name='employers_j_salary__2e8a5c_idx'), models.Index(fields=['is_featured', 'status', 'created_at'], name='employers_j_is_feat_082c28_idx'), models.Index(fields=['status', 'is_featured', '-created_at'], name='employers_j_status_268f3a_idx')],
            },
        ),
    ]
