# Generated by Django 6.0.1 on 2026-02-09 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_answer_scoring'),
        ('core', '0002_day36_question_engine'),
    ]

    operations = [
    ]
