# Generated by Django 6.0.1 on 2026-02-09 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_0002_answer_scoring_0002_day36_question_engine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiconversationturn',
            name='ai_annotations',
        ),
        migrations.RemoveField(
            model_name='aiconversationturn',
            name='answer_score',
        ),
        migrations.RemoveField(
            model_name='aiconversationturn',
            name='completeness_score',
        ),
        migrations.RemoveField(
            model_name='aiconversationturn',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='aiconversationturn',
            name='keyword_matches',
        ),
        migrations.RemoveField(
            model_name='aiconversationturn',
            name='relevance_score',
        ),
        migrations.RemoveField(
            model_name='aiinterviewsession',
            name='category_scores',
        ),
        migrations.RemoveField(
            model_name='aiinterviewsession',
            name='overall_score',
        ),
    ]
