# Generated by Django 5.2.8 on 2026-01-30 11:27

from django.db import migrations, models


def update_existing_skills(apps, schema_editor):
    Candidate = apps.get_model('core', 'Candidate')
    for candidate in Candidate.objects.all():
        if candidate.skills:
            # Convert any existing string data to empty dict
            candidate.skills = ""
            candidate.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='education',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='candidate',
            name='expected_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='employer',
            name='company_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='company_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employer',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RunPython(update_existing_skills),
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]