# Generated by Django 6.0.1 on 2026-02-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_aiconversationturn_ai_annotations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversationturn',
            name='ai_annotations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aiconversationturn',
            name='answer_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiconversationturn',
            name='completeness_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiconversationturn',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiconversationturn',
            name='keyword_matches',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aiconversationturn',
            name='relevance_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinterviewsession',
            name='category_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aiinterviewsession',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
