# Generated by Django 6.0.1 on 2026-01-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_profile_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='industry',
        ),
    ]
