# Generated by Django 6.0.1 on 2026-02-09 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_interview_scheduling'),
        ('core', '0005_aiconversationturn_ai_annotations_and_more'),
    ]

    operations = [
    ]
