# Generated by Django 6.0.1 on 2026-02-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20260209_1422'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='availabilityslot',
            new_name='core_availa_user_id_83a1db_idx',
            old_name='core_availa_user_id_d8e9a1_idx',
        ),
        migrations.RenameIndex(
            model_name='interviewschedule',
            new_name='core_interv_status_4a2347_idx',
            old_name='core_interv_status_f8c2d4_idx',
        ),
        migrations.RenameIndex(
            model_name='interviewschedule',
            new_name='core_interv_applica_7edc4b_idx',
            old_name='core_interv_applica_a3b5e7_idx',
        ),
    ]
