# Generated by Django 5.2.8 on 2026-01-30 11:39

from django.db import migrations

def clear_invalid_skills(apps, schema_editor):
    Candidate = apps.get_model('core', 'Candidate')
    # Clear all skills data to avoid JSON validation issues
    Candidate.objects.all().update(skills='')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_employer_industry'),
    ]

    operations = [
        migrations.RunPython(clear_invalid_skills),
    ]
