# Generated by Django 6.0.1 on 2026-02-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_interview_reminders'),
        ('core', '0007_rename_core_availa_user_id_d8e9a1_idx_core_availa_user_id_83a1db_idx_and_more'),
    ]

    operations = [
    ]
