# Generated by Django 6.0.1 on 2026-02-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20260209_1657'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='interviewreminder',
            new_name='core_interv_status_8a5652_idx',
            old_name='core_interv_status_idx',
        ),
    ]
