# Generated by Django 5.2.8 on 2026-01-30 12:49

import common.utils.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_employer_domain_employer_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=common.utils.file_validators.resume_upload_path, validators=[common.utils.file_validators.FileValidator()]),
        ),
    ]
