# Generated by Django 5.2.8 on 2026-01-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='application',
            new_name='core_applic_status_c418f1_idx',
            old_name='core_application_status_applied_idx',
        ),
        migrations.RenameIndex(
            model_name='application',
            new_name='core_applic_candida_94fcd8_idx',
            old_name='core_application_candidate_applied_idx',
        ),
        migrations.RenameIndex(
            model_name='application',
            new_name='core_applic_job_id_ef94e9_idx',
            old_name='core_application_job_applied_idx',
        ),
        migrations.RenameIndex(
            model_name='candidate',
            new_name='core_candid_experie_975ecb_idx',
            old_name='core_candidate_exp_salary_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='core_job_status_38dcf0_idx',
            old_name='core_job_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='core_job_locatio_dd2fb6_idx',
            old_name='core_job_location_status_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='core_job_title_096ba3_idx',
            old_name='core_job_title_status_idx',
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
