# Generated by Django 5.2.8 on 2026-01-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_job_experience_job_job_type_job_salary_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_featured', 'status', 'created_at'], name='core_job_is_feat_480887_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'is_featured', '-created_at'], name='core_job_status_c8839d_idx'),
        ),
    ]
