# Generated by Django 5.2.8 on 2026-01-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_job_is_featured_job_core_job_is_feat_480887_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume_snapshot',
            field=models.FileField(blank=True, null=True, upload_to='application_resumes/'),
        ),
    ]
