# Generated by Django 5.2.8 on 2026-02-02 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_application_candidate_remove_employer_user_and_more'),
    ]

    operations = [
    ]
