# Generated by Django 6.0.1 on 2026-02-07 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_emaillog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='core_emaill_status_45c927_idx',
            old_name='core_emaill_status_idx',
        ),
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='core_emaill_recipie_069a78_idx',
            old_name='core_emaill_recipient_idx',
        ),
    ]
