# Generated by Django 6.0.1 on 2026-02-08 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_core_emaill_status_idx_core_emaill_status_45c927_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICallQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('error_message', models.TextField(blank=True)),
                ('call_duration', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_calls', to='core.application')),
            ],
            options={
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='core_aicall_status_aaedaa_idx')],
            },
        ),
    ]
