# Generated by Django 6.0.1 on 2026-02-08 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_aicallqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicallqueue',
            name='call_outcome',
            field=models.CharField(choices=[('pending', 'Pending'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('callback_requested', 'Callback Requested'), ('no_response', 'No Response')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='aicallqueue',
            name='conversation_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aicallqueue',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aicallqueue',
            name='trigger_reason',
            field=models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='aicallqueue',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AIInterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('transcript_json', models.JSONField(blank=True, default=dict)),
                ('full_transcript_text', models.TextField(blank=True)),
                ('total_questions', models.IntegerField(default=0)),
                ('total_answers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call_queue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='core.aicallqueue')),
            ],
        ),
        migrations.CreateModel(
            name='AICallTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_audio_url', models.URLField(blank=True)),
                ('transcript_text', models.TextField()),
                ('transcript_json', models.JSONField(default=dict)),
                ('language', models.CharField(default='en', max_length=10)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='core.aiinterviewsession')),
            ],
        ),
        migrations.CreateModel(
            name='AIConversationTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='core.aiinterviewsession')),
            ],
            options={
                'ordering': ['turn_number'],
                'unique_together': {('session', 'turn_number')},
            },
        ),
    ]
