# Generated by Django 5.2.8 on 2026-02-02 14:43

import common.utils.file_validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.JSONField(blank=True, default=dict)),
                ('education', models.CharField(blank=True, max_length=200)),
                ('experience', models.CharField(blank=True, max_length=500)),
                ('expected_salary', models.IntegerField(blank=True, db_index=True, null=True)),
                ('experience_years', models.IntegerField(db_index=True, default=0)),
                ('resume', models.FileField(blank=True, null=True, upload_to=common.utils.file_validators.resume_upload_path, validators=[common.utils.file_validators.FileValidator()])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['experience_years', 'expected_salary'], name='candidates__experie_0d4600_idx')],
            },
        ),
    ]
